### ISSUE TITLE
Doesn't work on quality inserters

### ISSUE THREAD

**Issue by EmilyV99** [ClaudeMetz/SimpleAdjustableInserters#3]
My space platform uses all Legendary Bulk Inserters- in order to rotate them using this, I need to downgrade them to normal quality, then change their settings, then upgrade them in-place to Legendary again, which is pretty annoying. Would be great if this could just work on quality.

**Comment by ClaudeMetz** [comment]
Huh well that was unexpected, I didn't test quality inserters because I just expected them to work. Fixed with the newest release, thank for the report!
